### ISSUE TITLE
IDE Fatal Errors 'kotlin.KotlinNullPointerException' when create a new project.

### ISSUE THREAD

**Issue by firdyfirdy** [dsa28s/android-studio-apple-m1#14]
Hello, did anyone can help me?
I face this error when I create a new project. Did I miss something?
btw, Thank you for this awesome project!
![image](https://user-images.githubusercontent.com/29134376/117218495-74b96300-ae2d-11eb-83ac-ab24819350a3.png)

The full of error message:
```kotlin.KotlinNullPointerException
	at com.android.tools.idea.templates.recipe.DefaultRecipeExecutor.contentEquals(DefaultRecipeExecutor.kt:627)
	at com.android.tools.idea.templates.recipe.DefaultRecipeExecutor.copy(DefaultRecipeExecutor.kt:277)
	at com.android.tools.idea.npw.module.recipes.androidProject.AndroidProjectRecipeKt.androidProjectRecipe(androidProjectRecipe.kt:56)
	at com.android.tools.idea.npw.module.recipes.androidProject.AndroidProjectRecipeKt.androidProjectRecipe$default(androidProjectRecipe.kt:31)
	at com.android.tools.idea.npw.model.NewProjectModel$ProjectTemplateRenderer$performCreateProject$recipe$1.invoke(NewProjectModel.kt:229)
	at com.android.tools.idea.npw.model.NewProjectModel$ProjectTemplateRenderer$performCreateProject$recipe$1.invoke(NewProjectModel.kt:228)
	at com.android.tools.idea.npw.model.NewTemplateRendererKt$doRender$1.run(NewTemplateRenderer.kt:98)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:112)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$1(WriteCommandAction.java:253)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1006)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:252)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:310)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:187)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:312)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:251)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:232)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:114)
	at com.android.tools.idea.npw.model.NewTemplateRendererKt.doRender(NewTemplateRenderer.kt:97)
	at com.android.tools.idea.npw.model.NewTemplateRendererKt.render(NewTemplateRenderer.kt:66)
	at com.android.tools.idea.npw.model.NewTemplateRendererKt.render(NewTemplateRenderer.kt:81)
	at com.android.tools.idea.npw.model.NewTemplateRendererKt.render$default(NewTemplateRenderer.kt:80)
	at com.android.tools.idea.npw.model.NewProjectModel$ProjectTemplateRenderer.performCreateProject(NewProjectModel.kt:232)
	at com.android.tools.idea.npw.model.NewProjectModel$ProjectTemplateRenderer.render(NewProjectModel.kt:206)
	at com.android.tools.idea.npw.model.MultiTemplateRenderer$countDown$2$1$3.run(MultiTemplateRenderer.kt:136)
	at com.intellij.openapi.application.WriteThread.lambda$submit$0(WriteThread.java:27)
	at com.intellij.openapi.application.WriteThread.lambda$submit$1(WriteThread.java:44)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:828)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLaterOnWriteThread$11(ApplicationImpl.java:817)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:828)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by firdyfirdy** [comment]
Update: it's work fine if I load from existing project (not create a new project)

**Comment by firdyfirdy** [comment]
Update: I don't know why, but, now it's work fine after I try to load some of my existing projects & create a new project after that.
so yeah, I think I need to close this issue.
